all: apt neovim

neovim:
	add-apt-repository ppa:neovim-ppa/unstable
	apt update
	apt install neovim

apt:
	apt-get install -y libbz2-dev libsqlite3-dev libssl-dev zlib1g-dev libreadline-dev libffi-dev
