[[plugins]]
repo = 'Yggdroot/indentLine'
hook_source = '''
    nnoremap <Space>i :IndentLinesToggle<CR>
    let g:indentLine_setColors = 1
    let g:indentLine_color_term = 239
    let g:indentLine_color_gui = '#65737E'
    let g:indentLine_char = '│'
'''
on_i = 1

############################################
# clang
############################################
[[plugins]]
repo = 'Shougo/neoinclude.vim'
hook_add = '''
    let g:neoinclude#paths = {
    \   'c': '/usr/local/opt/allegro/include',
    \   'cpp': '/usr/local/opt/allegro/include',
    \}
'''
on_source = 'deoplete'
on_ft = ['c', 'cpp', 'cmake']

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp', 'cmake']
# on_if = 1

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source = '''
    if has('mac')
        let g:deoplete#sources#clang#libclang_path = '/usr/local/opt/llvm/lib/libclang.dylib'
        let g:deoplete#sources#clang#clang_header = '/usr/local/opt/llvm/lib/clang'
    else
        let g:deoplete#sources#clang#libclang_path = '/usr/lib64/libclang.so'
        let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
    endif
'''
on_ft = ['c', 'cpp', 'cmake']
on_source = ['deoplete']

[[plugins]]
repo = 'zebult/auto-gtags.vim'
hook_add = '''
    let g:auto_gtags = 1
    source ~/dotfiles/vim/rc/plugins/gtags.vim
'''
on_ft = ['c', 'cpp', 'cmake']

############################################
# C#
############################################
# [[plugins]]
# repo = "OmniSharp/omnisharp-vim"
# on_ft = ["cs"]
# hook_source = '''
#     let g:OmniSharp_server_path = g:config_dir . '/rc/plugins/OmniSharp.exe'
#     let g:OmniSharp_server_use_mono = 1
# '''

# [[plugins]]
# repo = "Robzz/deoplete-omnisharp"
# on_source = ['deoplete']
# on_ft = ["cs"]

# dimixar/deoplete-omnisharp


# [[plugins]]
# repo = 'cyansprite/omnisharp.nvim'
# build = ['./install.sh']
# hook_source = '''
#     let g:deoplete_omnisharp_exe_path = get(g:, "deoplete_omnisharp_exe_path", g:cache_dir . '/dein/repos/github.com/cyansprite/omnisharp.nvim/omnisharp-server/OmniSharp/bin/Debug/OmniSharp.exe')
#     let g:OmniSharp_server_path = g:config_dir . '/dein/repos/github.com/cyansprite/omnisharp.nvim/omnisharp-server/OmniSharp/bin/Debug/OmniSharp.exe'
#     let g:deoplete_omnisharp_port = get(g:, "deoplete_omnisharp_port", 2000)
# '''
# on_ft = 'cs'

############################################
# ruby
############################################
# [[plugins]]
# repo = 'uplus/deoplete-solargraph'
# on_source = ['deoplete.nvim']
# on_ft = 'ruby'
# hook_source = '''
# '''

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'
hook_source = '''
    "let g:monster#completion#rcodetools#backend = "async_rct_complete"
    let g:monster#completion#solargraph#backend = "async_solargraph_suggest"
'''
depends = 'vimproc.vim'


############################################
# go
############################################
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'
on_source = ['deoplete']

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
    " let g:echodoc#type = 'signature'
    call echodoc#enable()
'''
