[[plugins]]
repo = "OmniSharp/omnisharp-vim"
on_ft = ["cs"]
build = "xbuild server/OmniSharp.sln"
# on_i = 2

[[plugins]]
repo = "Robzz/deoplete-omnisharp"
on_source = ['deoplete']
on_ft = ["cs"]
on_i = 1
