[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    let g:NERDTreeShowLineNumbers = 1
    let g:NERDTreeWinSize = 25
    "nmap <Space>n :NERDTreeToggle<CR>
    nmap <leader>f :NERDTreeFind<Space>
    autocmd MyAutoCmd StdinReadPre * let s:std_in=1
    autocmd MyAutoCmd VimEnter * if (argc() == 0 && !exists("s:std_in")) | :NERDTreeToggle | endif
    autocmd MyAutoCmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | quit | endif
'''
on_event = 'VimEnter'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
    nmap <Space>n :NERDTreeTabsToggle<CR>
    let g:nerdtree_tabs_open_on_console_startup=1
'''
on_source = 'nerdtree'

[[plugins]]
repo = 'preservim/nerdcommenter'
hook_source = '''
    nmap <Space>c <Plug>NERDCommenterToggle
    smap <Space>c <Plug>NERDCommenterToggle
    xmap <Space>c <Plug>NERDCommenterToggle

    let g:NERDSpaceDelims = 1
    let g:NERDDefaultAlign = 'left'

    let g:NERDCustomDelimiters = {
            \ 'c': {'left': '//', 'leftAlt': '/**', 'rightAlt': '*/'},
            \ 'gp': {'left': '#'}
            \}
'''
on_event = ['BufEnter']
