[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'kana/vim-fakeclip'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeShowLineNumbers = 1
    let g:NERDTreeWinSize = 25
    nmap <Space>n :NERDTreeToggle<CR>
    autocmd MyAutoCmd StdinReadPre * let s:std_in=1
    autocmd MyAutoCmd VimEnter * if (argc() == 0 && !exists("s:std_in")) | :NERDTreeToggle | endif
    autocmd MyAutoCmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | quit | endif
'''
on_event = 'VimEnter'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_source = '''
    nmap <Space>c <Plug>NERDCommenterToggle
    smap <Space>c <Plug>NERDCommenterToggle
    xmap <Space>c <Plug>NERDCommenterToggle

    let g:NERDSpaceDelims = 1
    let g:NERDDefaultAlign = 'left'

    let g:NERDCustomDelimiters = { 'c': { 'left': '//', 'leftAlt': '/**', 'rightAlt': '*/'} }
'''
# on_i = 1
on_event = ['BufEnter']

# [[plugins]]
# repo = 'kana/vim-submode'
# hook_post_source = '''
#     call submode#enter_with('bufmove', 'n', '', 's>', '<C-w>>')
#     call submode#enter_with('bufmove', 'n', '', 's<', '<C-w><')
#     call submode#enter_with('bufmove', 'n', '', 's+', '<C-w>+')
#     call submode#enter_with('bufmove', 'n', '', 's-', '<C-w>-')
#     call submode#map('bufmove', 'n', '', '>', '<C-w>>')
#     call submode#map('bufmove', 'n', '', '<', '<C-w><')
#     call submode#map('bufmove', 'n', '', '+', '<C-w>+')
#     call submode#map('bufmove', 'n', '', '-', '<C-w>-')
# '''
# on_if = 1

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'severin-lemaignan/vim-minimap'
on_i = 1

# [[plugins]]
# repo = 'hisaknown/nanomap.vim'
# on_i = 1


[[plugins]]
repo = 'edkolev/tmuxline.vim'
on_i = 1
hook_source = '''
    " let g:tmuxline_powerline_separators = 0
    let g:tmuxline_theme = 'lightline'
    " let g:tmuxline_preset = 'tmux'
    " let g:tmuxline_preset = {
    "       \'a'    : '#S',
    "       \'c'    : ['#(whoami)', '#(uptime | cut -d " " -f 1,2,3)'],
    "       \'win'  : ['#I', '#W'],
    "       \'cwin' : ['#I', '#W', '#F'],
    "       \'x'    : '#(date)',
    "       \'y'    : ['%R', '%a', '%Y'],
    "       \'z'    : '#H'}
'''
