
# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'
# hook_source = '''
# if executable('cquery')
#    au User lsp_setup call lsp#register_server({
#       \ 'name': 'cquery',
#       \ 'cmd': {server_info->['cquery']},
#       \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
#       \ 'initialization_options': { 'cacheDirectory': '~/.cache/cquery/cache' },
#       \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
#       \ })
# endif
# '''

# [[plugins]]
# # repo = 'pdavydov108/vim-lsp-cquery'
# repo = 'Shougo/deoplete-lsp'
# hook_source = '''
# "call lsp#server#add('c', 'cquery')
# "call lsp#server#add('cpp', 'cquery')
# "call lsp#server#add('cc', 'cquery')
# '''
# on_ft = ['c', 'cpp', 'cc']

# [[plugins]]
# repo = 'thomasfaingnaert/vim-lsp-snippets'
# on_source = 'neosnippet.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

hook_add = '''
let g:coc_status_error_sign = "\uf00d"
let g:coc_status_warning_sign = "\uf12a"
'''
