
[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = 'pug'

[[plugins]]
repo = 'vim-scripts/fish-syntax'
on_ft = 'fish'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# [[plugins]] # switch filetype
# repo = 'osyo-manga/vim-precious'
# depends = 'context_filetype.vim'
# on_if = 1

# [[plugins]] # filetype
# repo = 'Shougo/context_filetype.vim'
# on_if = 1

# [[plugins]]
# repo = 'inkarkat/vim-ingo-library'
#
# [[plugins]]
# repo = 'inkarkat/vim-SyntaxRange'
# depands = ['vim-ingo-library']
# hook_source = '''
#     augroup SyntaxRangeConfig
#         autocmd!
#         autocmd BufNewFile,BufRead *.toml call s:syntax_range_dein()
#         function! s:syntax_range_dein() abort
#             let start = '^\s*hook_\%('.
#                         \           'add\|source\|post_source\|post_update'.
#                         \           '\)\s*=\s*%s'
#
#             call SyntaxRange#Include(printf(start, "'''"), "'''", 'vim', '')
#             call SyntaxRange#Include(printf(start, '"""'), '"""', 'vim', '')
#         endfunction
#     augroup END
# '''
