
# [[plugins]]
# repo = 'vim-latex/vim-latex'
# hook_add = '''
#     set shellslash
#     set grepprg=grep\ -nH\ $*
#     let g:tex_flavor='latex'
#     let g:Imap_UsePlaceHolders = 1
#     let g:Imap_DeleteEmptyPlaceHolders = 1
#     let g:Imap_StickyPlaceHolders = 0
#     let g:Tex_DefaultTargetFormat = 'dvi'
#     let g:Tex_MultipleCompileFormats='dvi,pdf'
#     let g:Tex_FormatDependency_pdf = 'dvi,pdf'
#     let g:Tex_CompileRule_dvi = 'platex -synctex=1 -interaction=nonstopmode -file-line-error $*'
#     let g:Tex_CompileRule_pdf = 'dvipdfmx $*.dvi'
#     let g:Tex_BibtexFlavor = 'upbibtex'
#     let g:Tex_MakeIndexFlavor = 'upmendex $*.idx'
#     let g:Tex_UseEditorSettingInDVIViewer = 1
#     let g:Tex_ViewRule_dvi = 'open -a /Applications/Skim.app'
#     let g:Tex_ViewRule_pdf = 'open -a /Applications/Preview.app'
# '''
# on_ft = 'tex'
# on_i = 1

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex', 'plaintex']
hook_source = '''
    let g:vimtex_compiler_latexmk = {
    \   'background': 1,
    \   'build_dir': '',
    \   'continuous': 1,
    \   'options': [
    \       '-pdfdvi',
    \       '-verbose',
    \       '-file-line-error',
    \       '-synctex=1',
    \       '-interaction=nonstopmode',
    \   ],
    \}

    let g:vimtex_fold_enabled = 1

    let g:vimtex_view_general_viewer
          \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
    let g:vimtex_view_general_options = '-g -r @line @pdf @tex'
'''

