
# [[plugins]]
# repo = 'vim-latex/vim-latex'
# hook_add = '''
#     set shellslash
#     set grepprg=grep\ -nH\ $*
#     let g:tex_flavor='latex'
#     let g:Imap_UsePlaceHolders = 1
#     let g:Imap_DeleteEmptyPlaceHolders = 1
#     let g:Imap_StickyPlaceHolders = 0
#     let g:Tex_DefaultTargetFormat = 'dvi'
#     let g:Tex_MultipleCompileFormats='dvi,pdf'
#     let g:Tex_FormatDependency_pdf = 'dvi,pdf'
#     let g:Tex_CompileRule_dvi = 'platex -synctex=1 -interaction=nonstopmode -file-line-error $*'
#     let g:Tex_CompileRule_pdf = 'dvipdfmx $*.dvi'
#     let g:Tex_BibtexFlavor = 'upbibtex'
#     let g:Tex_MakeIndexFlavor = 'upmendex $*.idx'
#     let g:Tex_UseEditorSettingInDVIViewer = 1
#     let g:Tex_ViewRule_dvi = 'open -a /Applications/Skim.app'
#     let g:Tex_ViewRule_pdf = 'open -a /Applications/Preview.app'
# '''
# on_ft = 'tex'
# on_i = 1

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
    let g:tex_flavor='latex'
    let g:vimtex_compiler_latexmk = {
    \   'background': 1,
    \   'build_dir': '',
    \   'continuous': 1,
    \   'options': [
    \       '-pdfdvi',
    \       '-verbose',
    \       '-file-line-error',
    \       '-synctex=1',
    \       '-interaction=nonstopmode',
    \   ],
    \}

    if has('mac')
        let g:vimtex_view_method='skim'
    else
        let g:vimtex_view_method='zathura'
    endif
    if has('nvim')
        let g:vimtex_compiler_progname = 'nvr'
    endif
    let g:vimtex_fold_enabled = 1

    let g:vimtex_view_general_viewer
          \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
    let g:vimtex_view_general_options = '-g -r @line @pdf @tex'

    let g:vimtex_quickfix_open_on_warning = 0

    let g:vimtex_quickfix_latexlog = {
    \    'default' : 1,
    \    'general' : 1,
    \    'references' : 1,
    \    'overfull' : 1,
    \    'underfull' : 1,
    \    'font' : 1,
    \    'packages' : {
    \        'default' : 1,
    \        'natbib' : 1,
    \        'biblatex' : 1,
    \        'babel' : 1,
    \        'hyperref' : 1,
    \        'scrreprt' : 1,
    \        'fixltx2e' : 1,
    \        'titlesec' : 1,
    \    },
    \}

'''

