
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'
hook_source = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
hook_source = '''
    let g:previm_open_cmd = 'open -a Firefox'
    let g:previm_disable_default_css = 1
    let g:previm_custom_css_path = g:config_dir . '/rc/plugins/markdown.css'
    let g:previm_enable_realtime = 1
'''
on_ft = 'markdown'

[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_i = 1

