
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_source = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_toc_autofit = 0
    let g:vim_markdown_math = 1
    let g:vim_markdown_folding_disabled = 1
    let g:tex_conceal = ""
    let g:vim_markdown_fenced_languages = [
        \ 'c++',
        \ 'c',
        \ 'shell',
        \ 'bash',
        \ 'java',
        \ 'ruby',
        \ 'python',
        \ 'json',
        \ 'xml',
        \ 'javascript',
        \ 'js=javascript'
    \]

'''

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'
hook_source = '''
    let g:previm_open_cmd = 'open -a Firefox'
    let g:previm_disable_default_css = 1
    let g:previm_custom_css_path = g:config_dir . '/rc/plugins/markdown.css'
    let g:previm_enable_realtime = 1
'''
on_ft = 'markdown'

[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_i = 1

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'
hook_source = '''
    let g:mkdp_auto_close = 0
    let g:mkdp_refresh_slow = 1
'''

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = 'markdown'

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'
