###########################################
# dain
###########################################


[[plugins]]
repo = 'joshdick/onedark.vim'

[plugins]]
epo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tyrannicaltoucan/vim-deep-space'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo ='nanotech/jellybeans.vim'

[[plugins]]
repo ='romainl/Apprentice'

[[plugins]]
repo = 'ajh17/Spacegray.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_theme = 'base16_oceanicnext'
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#wordcount#enabled = 1
    let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']



###########################################
# lazy
###########################################

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'


[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'

[[plugins]]
repo = 'Shougo/denite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'google/vim-maktaba'

[[plugins]]
repo = 'google/vim-codefmt'

[[plugins]]
repo = 'google/vim-glaive'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = '''
#     let g:indent_guides_enable_on_vim_startup = 1
#     set ts=4 sw=4 et
#     let g:indent_guides_start_level = 2
#     let g:indent_guides_guide_size = 1
# '''
