augroup MyAutoCmd
    autocmd!
augroup END

let g:python_host_prog = expand('$PYENV_ROOT/versions/2.7.14/bin/python')
let g:python3_host_prog = expand('$PYENV_ROOT/versions/3.6.4/bin/python')

" if has('nvim')
"     let g:vim_home = expand('~/dotfiles/nvim')
"     let g:rc_dir = expand('~/dotfiles/nvim/rc')
" else
"     let g:vim_home = expand('~/dotfiles/vim')
"     let g:rc_dir = expand('~/dotfiles/vim/rc')
" endif

let g:vim_home = expand('~/dotfiles/vim')
let g:rc_dir = expand('~/dotfiles/vim/rc')


" rcファイル読み込み関数
function! s:source_rc(rc_file_name)
    let l:rc_file = expand(g:rc_dir . '/' . a:rc_file_name)
    if filereadable(l:rc_file)
        execute 'source' l:rc_file
    endif
endfunction

if !has('vim')
    call s:source_rc('dein.rc.vim')
endif

call s:source_rc('editor.rc.vim')

call s:source_rc('clipboard.rc.vim')

call s:source_rc('color.rc.vim')

call s:source_rc('mappings.rc.vim')

call s:source_rc('filetypes.rc.vim')

call s:source_rc('windowctrl.rc.vim')


 call s:source_rc('syntaxinfo..rc.vim')
" call s:source_rc('status_line.rc.vim')

