# [[plugins]]
# repo = 'majutsushi/tagbar'
# hook_source = '''
#     let g:tagbar_width = 30
#     let g:tagbar_autoshowtag = 1
#     " let g:tagbar_autofocus = 1
#     let g:tagbar_show_linenumbers = 1
#     let g:tagbar_sort = 0
#     let g:tagbar_left = 1

#     let g:tagbar_type_go = {
#         \ 'ctagstype' : 'go',
#         \ 'kinds'     : [
#             \ 'p:package',
#             \ 'i:imports:1',
#             \ 'c:constants',
#             \ 'v:variables',
#             \ 't:types',
#             \ 'n:interfaces',
#             \ 'w:fields',
#             \ 'e:embedded',
#             \ 'm:methods',
#             \ 'r:constructor',
#             \ 'f:functions'
#         \ ],
#         \ 'sro' : '.',
#         \ 'kind2scope' : {
#                 \ 't' : 'ctype',
#                 \ 'n' : 'ntype'
#         \ },
#         \ 'scope2kind' : {
#             \ 'ctype' : 't',
#             \ 'ntype' : 'n'
#         \ },
#         \ 'ctagsbin'  : 'gotags',
#         \ 'ctagsargs' : '-sort -silent'
#         \ }
# '''
# hook_add = '''
#     nmap <Space>t :TagbarToggle<CR>
# '''
# on_if = 1

[[plugins]]
repo = 'sarub0b0/lldb.nvim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'vim-jp/vital.vim'
merged = 0

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = 'graphql'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_add = '''
"let g:context_filetype#filetypes = {
"\'vue': [
"\  {
"\     'start': '^<template.*>',
"\     'end': '^<\/template>',
"\     'filetype': 'html'
"\  }
"\]
"\}
'''
on_ft = 'vue'

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
    let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue,*.js'
    let g:closetag_filetypes = 'html,xhtml,phtml,erb,php,vue,javascript'
'''
on_ft = ['vue', 'html', 'xhtml', 'phtml', 'erb', 'php', 'javascript']

