# [[plugins]]
# repo = 'majutsushi/tagbar'
# hook_source = '''
#     let g:tagbar_width = 30
#     let g:tagbar_autoshowtag = 1
#     " let g:tagbar_autofocus = 1
#     let g:tagbar_show_linenumbers = 1
#     let g:tagbar_sort = 0
#     let g:tagbar_left = 1

#     let g:tagbar_type_go = {
#         \ 'ctagstype' : 'go',
#         \ 'kinds'     : [
#             \ 'p:package',
#             \ 'i:imports:1',
#             \ 'c:constants',
#             \ 'v:variables',
#             \ 't:types',
#             \ 'n:interfaces',
#             \ 'w:fields',
#             \ 'e:embedded',
#             \ 'm:methods',
#             \ 'r:constructor',
#             \ 'f:functions'
#         \ ],
#         \ 'sro' : '.',
#         \ 'kind2scope' : {
#                 \ 't' : 'ctype',
#                 \ 'n' : 'ntype'
#         \ },
#         \ 'scope2kind' : {
#             \ 'ctype' : 't',
#             \ 'ntype' : 'n'
#         \ },
#         \ 'ctagsbin'  : 'gotags',
#         \ 'ctagsargs' : '-sort -silent'
#         \ }
# '''
# hook_add = '''
#     nmap <Space>t :TagbarToggle<CR>
# '''
# on_if = 1

[[plugins]]
repo = 'sarub0b0/lldb.nvim'
on_ft = ['c', 'cpp']
