[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_i = 1

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = 'markdown'
hook_source = '''
    let g:mkdp_auto_start = 0
    let g:mkdp_auto_close = 1
    let g:mkdp_refresh_slow = 0
'''

[[plugins]]
repo = 'iamcco/mathjax-support-for-mkdp'
on_ft = 'markdown'

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'
